version: "3.9"

services:
  webserver:
    container_name: mygoapp
    image: jorgeteixe/goapp:simple
    networks:
      smr:
        aliases:
          - "server"
  webclient:
    container_name: client
    image: jorgeteixe/webclient:latest
    command: "/script.sh"
    volumes:
      - ./script.sh:/script.sh:ro
    networks:
      - smr

networks:
  smr:
    name: 'smr'
