apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-v1-deployment
  labels:
    app: versions-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: versions-v1
  template:
    metadata:
      labels:
        app: versions-v1
    spec:
      containers:
      - name: goversions-v1
        image: jorgeteixe/goversions:v1
        ports:
        - containerPort: 8090
