apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
data:
  mysql_host: db.jtei.io
  mysql_db: asir
  mysql_user: asir
---
apiVersion: v1
kind: Secret
metadata:
  name: go-api-secret
type: Opaque
data:
  mysql_pass: YWJjMTIzLg==
