apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  labels:
    app: go-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: jorgeteixe/goexampleapi:latest
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: go-api-config
              key: mysql_host
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: go-api-config
              key: mysql_db
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: go-api-config
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-api-secret
              key: mysql_pass
        ports:
        - containerPort: 8090
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /ok
            port: 8090
        readinessProbe:
          httpGet:
            path: /ok
            port: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: go-api-service
spec:
  selector:
    app: go-api
  ports:
    - port: 8090
